<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class DummyDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Siswa
        DB::table('students')->insert([
            [
                'nis' => 'S001',
                'full_name' => 'Andi Saputra',
                'gender' => 'M',
                'birth_place' => 'Jakarta',
                'birth_date' => '2008-05-01',
                'address' => 'Jl. Merdeka No.1',
                'phone' => '081234567891',
                'email' => 'andi@example.com',
                'religion' => 'Islam',
                'enrollment_year' => '2022',
                'guardian_name' => 'Budi Saputra',
                'guardian_phone' => '081234567890',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nis' => 'S002',
                'full_name' => 'Raden Maulana',
                'gender' => 'M',
                'birth_place' => 'Bandung',
                'birth_date' => '2009-02-11',
                'address' => 'Jl. Siliwangi No.2',
                'phone' => '081234567892',
                'email' => 'raden@example.com',
                'religion' => 'Islam',
                'enrollment_year' => '2022',
                'guardian_name' => 'Siti Maulana',
                'guardian_phone' => '081234567891',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nis' => 'S003',
                'full_name' => 'Bagas Pratama',
                'gender' => 'M',
                'birth_place' => 'Surabaya',
                'birth_date' => '2008-08-15',
                'address' => 'Jl. Pahlawan No.3',
                'phone' => '081234567893',
                'email' => 'bagas@example.com',
                'religion' => 'Kristen',
                'enrollment_year' => '2022',
                'guardian_name' => 'Yuni Pratama',
                'guardian_phone' => '081234567892',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nis' => 'S004',
                'full_name' => 'Andre Kurniawan',
                'gender' => 'M',
                'birth_place' => 'Medan',
                'birth_date' => '2008-12-30',
                'address' => 'Jl. Jamin Ginting No.4',
                'phone' => '081234567894',
                'email' => 'andre@example.com',
                'religion' => 'Islam',
                'enrollment_year' => '2022',
                'guardian_name' => 'Asep Kurniawan',
                'guardian_phone' => '081234567893',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nis' => 'S005',
                'full_name' => 'Adrian Putra',
                'gender' => 'M',
                'birth_place' => 'Semarang',
                'birth_date' => '2009-04-21',
                'address' => 'Jl. Pemuda No.5',
                'phone' => '081234567895',
                'email' => 'adrian@example.com',
                'religion' => 'Katolik',
                'enrollment_year' => '2022',
                'guardian_name' => 'Lina Putra',
                'guardian_phone' => '081234567894',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nis' => 'S006',
                'full_name' => 'Salma Nuraini',
                'gender' => 'F',
                'birth_place' => 'Yogyakarta',
                'birth_date' => '2008-09-12',
                'address' => 'Jl. Kaliurang No.6',
                'phone' => '081234567896',
                'email' => 'salma@example.com',
                'religion' => 'Islam',
                'enrollment_year' => '2022',
                'guardian_name' => 'Dewi Nuraini',
                'guardian_phone' => '081234567895',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Guru
        DB::table('teachers')->insert([
            [
                'nip' => 'T001',
                'full_name' => 'Pak Andi',
                'gender' => 'M',
                'birth_place' => 'Jakarta',
                'birth_date' => '1980-01-01',
                'address' => 'Jl. Pendidikan No.1',
                'phone' => '081234567801',
                'email' => 'pak.andi@example.com',
                'religion' => 'Islam',
                'enrollment_year' => '2010',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => 'T002',
                'full_name' => 'Bu Salma',
                'gender' => 'F',
                'birth_place' => 'Bandung',
                'birth_date' => '1985-02-02',
                'address' => 'Jl. Guru No.2',
                'phone' => '081234567802',
                'email' => 'bu.salma@example.com',
                'religion' => 'Islam',
                'enrollment_year' => '2012',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => 'T003',
                'full_name' => 'Pak Raden',
                'gender' => 'M',
                'birth_place' => 'Surabaya',
                'birth_date' => '1975-03-03',
                'address' => 'Jl. Ilmu No.3',
                'phone' => '081234567803',
                'email' => 'pak.raden@example.com',
                'religion' => 'Kristen',
                'enrollment_year' => '2008',
                'photo' => null,
                'status' => 'active',
                'class_id' => null,
                'user_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
